version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3308:3307
    environment:
      - MYSQL_DATABASE=quiz_practice
      - MYSQL_USER=quiz_practice
      - MYSQL_PASSWORD=quiz_practice
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

